---
name: Publish site

'on':
  push:
    branches:
      - publish
  pull_request:
    branches:
      - publish

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: trunk

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages

      - name: Get the publish cli
        run: git clone https://github.com/JohnSundell/Publish.git

      - name: Restore the Publish cache
        uses: actions/cache@v2
        with:
          path: Publish/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build the publish cli
        run: cd Publish && make

      - name: Restore the Publish cache
        uses: actions/cache@v2
        with:
          path: trunk/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Generate the site
        run: cd trunk && publish generate

      - name: Prepare to publish the site
        run: |
          cd pages/
          git rm -rf *

      - name: Move data from source to output
        run: mv trunk/Output/* pages/

      - name: Publish the site
        run: |
          cd pages/
          ls .
          git add .
          git commit -am "Publish $(date)"
          git push
